recipe: default.v1
assistant_id: rasa_upis
language: sr

pipeline:

policies:
  - name: MemoizationPolicy
  - name: RulePolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 100
    constrain_similarities: true
