recipe: default.v1
assistant_id: rasa_upis
language: sr

pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer

policies:
  - name: MemoizationPolicy
  - name: RulePolicy
  - name: UnexpecTEDIntentPolicy
    max_history: 5
    epochs: 100
  - name: TEDPolicy
    max_history: 5
    epochs: 100
    constrain_similarities: true
